server:
  port: 8080
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      jdbc-url: jdbc:oracle:thin:@db_name_high?TNS_ADMIN=/path/to/wallet
      driver-class-name: oracle.jdbc.OracleDriver
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      pool-name: BbangBuddyHikariCP
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 600000
      max-lifetime: 2000000
      connection-timeout: 30000

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: none # don't touch!
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
    show-sql: true

firebase:
  config-path: /Users/deepsea/Documents/study/project/bbang-buddy/config/firebase-adminsdk.json

pot:
  image:
    upload:
      #path: ${user.dir}/uploads/potimages
      #path: /Users/deepsea/Documents/study/project/bbang-buddy-api/bbang-buddy-api/uploads/potimages
      path: /Users/deepsea/Documents/study/project/bbang-buddy-ui/public

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
    org.hibernate.type.descriptor.sql.BasicBinder: trace

jwt:
  secret: ZOzaIiOyvlTtZN++0W5ZirvA7n8NXzCkIVodGL4tMRbIj77tioO3CIJhM84yHrjDqmUr+yxcTsSw6JQtwxaDgg==
  token-validity-in-seconds: 3600
  refresh-token-validity-in-seconds: 604800
  expiration: 86400000 # 24 hours

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    chat-id: ${TELEGRAM_CHAT_ID}